basePath: /
definitions:
  model.GithubRepoBranchResponse:
    properties:
      branchName:
        type: string
      lastCommitSHA:
        type: string
    type: object
  model.GithubRepoResponse:
    properties:
      branches:
        items:
          $ref: '#/definitions/model.GithubRepoBranchResponse'
        type: array
      ownerLogin:
        type: string
      repoName:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Server to get the information about the user & repo from github using
    Github Public APIs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Go-Github Service API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - root
  /api/v1/{github_username}/repos:
    get:
      consumes:
      - application/json
      description: Get the User Github Profile and Repo information using public Github
        APIs
      parameters:
      - description: string valid
        in: path
        name: github_username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.GithubRepoResponse'
            type: array
      summary: Get the User Github Profile and Repo information.
      tags:
      - root
schemes:
- http
swagger: "2.0"
